# cargo

# [[file:~/Workspace/Programming/gosh-rs/runners/runners.note::*cargo][cargo:1]]
[package]
name = "runners"
version = "0.0.2"
edition = "2018"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[dependencies]
structopt = "0.2"
quicli = "0.4"
chrono = "0.4"
duct = "0.12"
ctrlc = "3.1"
crossbeam-channel = "0.3"
tempfile = "3.0"
rocket = "0.4"
# mpi = { git = "https://github.com/bsteinb/rsmpi", rev = "f9aec8b8d82" }
#mpi = "0.5"

[dev-dependencies]
# cargo:1 ends here
